---
- name: Create mtproxy directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: docker
    mode: "0755"
  with_items:
    - "{{ mtproxy_conf_dir }}"
    - "{{ mtproxy_data_dir }}"

- name: Create mtproxy docker config
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ mtproxy_conf_dir }}/docker-compose.yml"
    owner: root
    group: docker
    mode: "0644"

- name: Docker Compose start containers
  community.docker.docker_compose_v2:
    project_src: "{{ mtproxy_conf_dir }}"
    files:
      - docker-compose.yml
    state: "{{ mtproxy_state }}"
    pull: "{{ mtproxy_force_pull | ternary('always', 'policy') }}"
    recreate: "{{ mtproxy_force_restart | ternary('always', 'auto') }}"

- name: List mtproxy urls https://t.me/proxy?server=${SEVER}&port=${PORT}&secret=dd${SECRET}
  ansible.builtin.debug:
    msg: |
      {% for item in mtproxy_secret %}
      https://t.me/proxy?server={{ inventory_hostname }}&port={{ mtproxy_https_port }}&secret=dd{{ item }}
      {% endfor %}
