---
- name: Create telemt directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: docker
    mode: "0755"
  with_items:
    - "{{ telemt_conf_dir }}"
    - "{{ telemt_data_dir }}"

- name: Create telemt config files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ telemt_conf_dir }}/{{ item | basename | regex_replace('.j2', '') }}"
    owner: root
    group: docker
    mode: "0644"
  loop:
    - docker-compose.yml.j2
    - config.toml.j2

- name: Docker Compose start containers
  community.docker.docker_compose_v2:
    project_src: "{{ telemt_conf_dir }}"
    files:
      - docker-compose.yml
    state: "{{ telemt_state }}"
    pull: "{{ telemt_force_pull | ternary('always', 'policy') }}"
    recreate: "{{ telemt_force_restart | ternary('always', 'auto') }}"

- name: Compute HEX_DOMAIN
  ansible.builtin.shell: printf '%s' "{{ telemt_tls_domain }}" | hexdump -v -e '/1 "%02x"'
  register: hex_domain
  changed_when: false
  check_mode: false

- name: List telemt urls https://t.me/proxy?server=${SEVER}&port=${PORT}&secret=${SECRET}
  ansible.builtin.debug:
    msg: |
      https://t.me/proxy?server={{ ansible_host }}&port={{ telemt_https_port }}&secret=ee{{ telemt_secret }}{{ hex_domain.stdout }}
