---
wgportal_version: latest

# wgportal datacenter
wgportal_datacenter: berlin
wgportal_timezone: Europe/Berlin

# wgportal directories
wgportal_conf_dir: /opt/wgportal
wgportal_data_dir: "/srv/wgportal/{{ wgportal_datacenter }}"

# docker compose options
wgportal_state: present
wgportal_force_pull: false
wgportal_force_restart: false
wgportal_mode: host
wgportal_hosts_file: {}

wgportal_admin_username: admin@wgportal.local
wgportal_admin_password: wgportal-default
