---
- name: Create zerotier directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: docker
    mode: "0755"
  with_items:
    - "{{ zerotier_conf_dir }}"
    - "{{ zerotier_data_dir }}"

- name: Create zerotier config files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ zerotier_conf_dir }}/{{ item | basename | regex_replace('.j2', '') }}"
    owner: root
    group: docker
    mode: "0644"
  loop:
    - docker-compose.yml.j2

- name: Docker Compose start containers
  community.docker.docker_compose_v2:
    project_src: "{{ zerotier_conf_dir }}"
    files:
      - docker-compose.yml
    state: "{{ zerotier_state }}"
    pull: "{{ zerotier_force_pull | ternary('always', 'policy') }}"
    recreate: "{{ zerotier_force_restart | ternary('always', 'auto') }}"
