---
telemt_version: latest

# telemt directories
telemt_conf_dir: /opt/telemt
telemt_data_dir: /srv/telemt

# telemt datacenter
telemt_datacenter: berlin
telemt_timezone: Europe/Berlin

# telemt ports
telemt_https_port: 443

# docker compose options
telemt_state: present
telemt_force_pull: false
telemt_force_restart: false
telemt_log_level: silent
telemt_tls_domain: googletagmanager.com
telemt_secret: "{{ lookup('ansible.builtin.password', '/dev/null', chars='0123456789abcdef', length=32, seed=inventory_hostname) }}"
telemt_hosts_file: {}
