---
- name: Docker Compose stop containers and remove images
  community.docker.docker_compose_v2:
    project_src: "{{ cloudflared_conf_dir }}"
    files:
      - docker-compose.yml
    state: absent
    remove_orphans: true
    remove_images: all
    renew_anon_volumes: true

- name: Purge cloudflared directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ cloudflared_conf_dir }}"
